### ISSUE TITLE
Ensure RFM works with RF 7.4

### ISSUE THREAD

**Issue by lczub** [lczub/robotframework-magik#44]
Running RFM tests on RF 7.4.1 PY 312 let fail all test during suite setup

```
Error in file '/home/lczub/Projects/robotframework-magik/tests/scripts/robot_magik_prompt_tests.robot' on line 25: Importing library '/home/lczub/Projects/robotframework-magik/resources/RobotMagikLauncher.py' failed: ImportError: cannot import name 'timestr_to_secs' from 'robot.libraries.Process' (/home/lczub/Projects/robotframework-magik/.venv/lib/python3.12/site-packages/robot/libraries/Process.py)
Traceback (most recent call last):
  File "/home/lczub/Projects/robotframework-magik/resources/RobotMagikLauncher.py", line 21, in <module>
    from robot.libraries.Process import Process, logger, timestr_to_secs
PYTHONPATH:
  /home/lczub/Projects/robotframework-magik/resources
  /home/lczub/Projects/robotframework-magik/lib
  /home/lczub/Projects/robotframework-magik/resources
  /home/lczub/.vscode-oss/extensions/d-biehl.robotcode-2.1.0-universal/bundled/libs
  /home/lczub/.vscode-oss/extensions/d-biehl.robotcode-2.1.0-universal/bundled/tool/robotcode
  /usr/lib/python312.zip
  /usr/lib/python3.12
  /usr/lib/python3.12/lib-dynload
  /home/lczub/Projects/robotframework-magik/.venv/lib/python3.12/site-packages
```

**Comment by lczub** [comment]
Analyse usage deprecated and changed functions described in [RF 74 release notes](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-7.4.rst) required.
